# Generated by Django 3.0.5 on 2022-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('CL', 'Cloths'), ('SW', 'SportWear'), ('OW', 'OutWear'), ('ET', 'Electronics'), ('RC', 'Recommended'), ('CW', 'Cookware')], max_length=2),
        ),
    ]
