# Generated by Django 3.0.5 on 2022-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyapp', '0002_auto_20220105_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('R', 'Razorpay'), ('I', 'Instamojo'), ('C', 'CCAvenue'), ('S', 'Stripe'), ('P', 'Paypal')], max_length=2),
        ),
    ]
